name: codeediter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  process_run: ^0.13.1
  process_runner: ^4.1.2
  path_provider: ^2.1.1
  file_manager: ^1.0.2
  filesystem_picker: ^3.1.0
  device_frame: ^1.1.0
#  device_preview: ^1.1.0
  desktop_window: ^0.4.0
  window_manager: ^0.3.7
#  flutter_box_transform: ^0.4.2
  adaptive_theme: ^3.2.1
#  easy_image_editor: ^1.0.3
  url_launcher: ^6.1.11
  provider: ^6.0.5
  equatable: ^2.0.5
  dart_style: ^2.3.1
  vector_math: ^2.1.4
#  flutter_colorpicker: ^1.0.3
  two_dimensional_scrollables: ^0.0.3
  popover: ^0.2.8+2
  mouse_follower: ^1.2.2
#  flutter_painter_v2: ^2.0.1

#  zoom_widget: ^2.0.1
#  two_dimensional_scrollables: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

